const products = [
  {
    _id: '1',
    name: 'Bag Military Black',
    image: '1.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora, veritatis!',
    brand: 'Benetton',
    category: 'Bags',
    price: 75.00,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Denim jacket blue',
    image: '2.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet exercitationem iure nostrum officia praesentium! Est ratione sint temporibus? Expedita nulla repudiandae ullam? Amet animi deserunt nam perspiciatis rem sunt, tempore.',
    brand: 'Mango',
    category: 'Clothes',
    price: 92.50,
    countInStock: 3,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Black watch',
    image: '3.jpg',
    description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad atque, deleniti, ea est, eveniet facere harum iste odio quibusdam ratione recusandae similique sit temporibus unde!',
    brand: 'Guess',
    category: 'Watches',
    price: 165.90,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Frayed denim shorts high waist',
    image: '4.jpg',
    description: 'Lorem ipsum dolor sit amet.',
    brand: 'Mango',
    category: 'Clothes',
    price: 29.50,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Сrossbody bag Glossy Silver',
    image: '5.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque beatae consectetur distinctio dolor enim fuga iure iusto maiores nam necessitatibus nesciunt nisi nobis numquam obcaecati omnis perspiciatis, praesentium quaerat, quidem quod rerum soluta vero voluptates. Beatae expedita odio repudiandae.',
    brand: 'Max Mara',
    category: 'Bags',
    price: 75.00,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Light grey shirt',
    image: '6.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta laborum odio officiis quidem. Alias consectetur consequuntur dicta. Vero?',
    brand: 'Benetton',
    category: 'Clothes',
    price: 92.50,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'White sneakers',
    image: '7.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora, veritatis!',
    brand: 'Benetton',
    category: 'Shoes',
    price: 75.00,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Brown watch',
    image: '8.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet exercitationem iure nostrum officia praesentium! Est ratione sint temporibus? Expedita nulla repudiandae ullam? Amet animi deserunt nam perspiciatis rem sunt, tempore.',
    brand: 'Mango',
    category: 'Watches',
    price: 92.50,
    countInStock: 3,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '9',
    name: 'T-shirt DF basic oversize long',
    image: '9.jpg',
    description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad atque, deleniti, ea est, eveniet facere harum iste odio quibusdam ratione recusandae similique sit temporibus unde!',
    brand: 'Guess',
    category: 'Clothes',
    price: 165.90,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Joggers Lounge light grey',
    image: '10.jpg',
    description: 'Lorem ipsum dolor sit amet.',
    brand: 'Mango',
    category: 'Clothes',
    price: 29.50,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Denim chill joggers',
    image: '11.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque beatae consectetur distinctio dolor enim fuga iure iusto maiores nam necessitatibus nesciunt nisi nobis numquam obcaecati omnis perspiciatis, praesentium quaerat, quidem quod rerum soluta vero voluptates. Beatae expedita odio repudiandae.',
    brand: 'Max Mara',
    category: 'Clothes',
    price: 75.00,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '12',
    name: 'White t-shirt basic',
    image: '12.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta laborum odio officiis quidem. Alias consectetur consequuntur dicta. Vero?',
    brand: 'Guess',
    category: 'Clothes',
    price: 92.50,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

export default products
